### ISSUE TITLE
关于「如何自助」文中的两个疑似错别字

### ISSUE THREAD

**Issue by yingbibanxain** [xiaolai/help-to-be-helped#3]
笑来老师：
**5. 潜意识的基础工作原理**
「我们的**意思**就好像是手机一样」应为「意识」

**13. 避免成为密切接触者**
「有没有**一生**都一样，最终你只能靠你自身的免疫力去战胜它」应为「医生」

请核实，感谢您的文章。

**Comment by xiaolai** [comment]
已经改过来了。
